# Generated by Django 5.0.4 on 2024-04-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='video_id',
        ),
        migrations.AddField(
            model_name='pin',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.videounit'),
        ),
    ]
