# Generated by Django 5.0.4 on 2024-04-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videounit_remove_pin_video_id_pin_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videounit'),
        ),
    ]
